// Code generated by generator/lookups/main.go; DO NOT EDIT.

package colors

import (
	"github.com/pborman/colors/crayola"
	"github.com/pborman/colors/pantone"
	"github.com/pborman/colors/web"
	"github.com/pborman/colors/x11"
	"image/color"
	"strings"
)

// FromString returns the color associated with the given name.
// It supports both exact matches and case-insensitive matches.
// This function checks the root package colors first, and if not found,
// falls back to checking colors in this order: web, x11, crayola, pantone.
func FromString(name string) (color.RGBA, bool) {
	lowerName := strings.ToLower(name)
	c, ok := nameToColor[lowerName]
	if ok {
		return c, true
	}
	c, ok = web.FromString(lowerName)
	if ok {
		return c, true
	}
	c, ok = x11.FromString(lowerName)
	if ok {
		return c, true
	}
	c, ok = crayola.FromString(lowerName)
	if ok {
		return c, true
	}
	c, ok = pantone.FromString(lowerName)
	if ok {
		return c, true
	}
	return color.RGBA{}, false
}

// ToString returns the name associated with the given color.
// If the color is not found, an empty string is returned.
// This function checks the root package colors first, and if not found,
// falls back to checking colors in this order: web, x11, crayola, pantone.
func ToString(c color.RGBA) string {
	name := colorToName[c]
	if name != "" {
		return name
	}
	name = web.ToString(c)
	if name != "" {
		return name
	}
	name = x11.ToString(c)
	if name != "" {
		return name
	}
	name = crayola.ToString(c)
	if name != "" {
		return name
	}
	name = pantone.ToString(c)
	if name != "" {
		return name
	}
	return ""
}
