package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type Color struct {
	Name string
}

func parseColors(path string) ([]Color, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}

	var colors []Color
	for _, decl := range f.Decls {
		if genDecl, ok := decl.(*ast.GenDecl); ok && genDecl.Tok == token.VAR {
			for _, spec := range genDecl.Specs {
				if valueSpec, ok := spec.(*ast.ValueSpec); ok {
					for _, name := range valueSpec.Names {
						colors = append(colors, Color{Name: name.Name})
					}
				}
			}
		}
	}
	return colors, nil
}

func main() {
	pkgs := []string{"crayola", "pantone", "web", "x11"}

	// Assuming the script is run from the project root
	for _, pkg := range pkgs {
		path := filepath.Join(pkg, pkg+".go")
		colors, err := parseColors(path)
		if err != nil {
			panic(err)
		}

		generateLookupFile(pkg, pkg, colors, false)
	}

	generateRootLookup()
}

const lookupTmpl = `// Code generated by generator/lookups/main.go; DO NOT EDIT.

package {{.Pkg}}

import (
	"image/color"
	"strings"
)

// FromString returns the color associated with the given name.
// It supports both exact matches and case-insensitive matches.
func FromString(name string) (color.RGBA, bool) {
	c, ok := nameToColor[strings.ToLower(name)]
	return c, ok
}

// ToString returns the name associated with the given color.
// If the color is not found, an empty string is returned.
func ToString(c color.RGBA) string {
	return colorToName[c]
}
`

const rootLookupTmpl = `// Code generated by generator/lookups/main.go; DO NOT EDIT.

package colors

import (
	"image/color"
	"strings"
{{- range .Pkgs}}
	"github.com/pborman/colors/{{.}}"
{{- end}}
)

// FromString returns the color associated with the given name.
// It supports both exact matches and case-insensitive matches.
// This function checks the root package colors first, and if not found,
// falls back to checking colors in this order: web, x11, crayola, pantone.
func FromString(name string) (color.RGBA, bool) {
	lowerName := strings.ToLower(name)
	c, ok := nameToColor[lowerName]
	if ok {
		return c, true
	}
{{- range .Pkgs}}
	c, ok = {{.}}.FromString(lowerName)
	if ok {
		return c, true
	}
{{- end}}
	return color.RGBA{}, false
}

// ToString returns the name associated with the given color.
// If the color is not found, an empty string is returned.
// This function checks the root package colors first, and if not found,
// falls back to checking colors in this order: web, x11, crayola, pantone.
func ToString(c color.RGBA) string {
	name := colorToName[c]
	if name != "" {
		return name
	}
{{- range .Pkgs}}
	name = {{.}}.ToString(c)
	if name != "" {
		return name
	}
{{- end}}
	return ""
}
`

const nameToColorTmpl = `// Code generated by generator/lookups/main.go; DO NOT EDIT.

package {{.Pkg}}

import "image/color"

var nameToColor = map[string]color.RGBA{
{{- range .Colors}}
	"{{lower .Name}}": {{.Name}},
{{- end}}
}
`

const colorToNameTmpl = `// Code generated by generator/lookups/main.go; DO NOT EDIT.

package {{.Pkg}}

import "image/color"

var colorToName = map[color.RGBA]string{
{{- range .Colors}}
	{{.Name}}: "{{.Name}}",
{{- end}}
}
`

const syncTestTmpl = `// Code generated by generator/lookups/main.go; DO NOT EDIT.

package {{.Pkg}}

import (
	"testing"
)

func TestMapSync(t *testing.T) {
	// Note: nameToColor maps unique lowercase names to color.RGBA.
	// colorToName maps unique color.RGBA values back to a name.
	// Because some colors map to the exact same color.RGBA value
	// (e.g. Gray and Grey), colorToName can have fewer elements than nameToColor.
	// This test simply verifies that both maps are correctly populated.

	if len(nameToColor) == 0 {
		t.Errorf("nameToColor is empty")
	}
	if len(colorToName) == 0 {
		t.Errorf("colorToName is empty")
	}
	if len(colorToName) > len(nameToColor) {
		t.Errorf("colorToName has more elements (%d) than nameToColor (%d), which should be impossible", len(colorToName), len(nameToColor))
	}
}
`

func generateLookupFile(pkgName, dir string, colors []Color, isRoot bool) {
	// 1. Generate lookup.go
	t := template.New("lookup")
	t.Funcs(template.FuncMap{"lower": strings.ToLower})

	tmpl := lookupTmpl
	if isRoot {
		tmpl = rootLookupTmpl
	}

	t, err := t.Parse(tmpl)
	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	err = t.Execute(&buf, struct {
		Pkg    string
		Pkgs   []string
	}{
		Pkg:    pkgName,
		Pkgs:   []string{"web", "x11", "crayola", "pantone"}, // priority order
	})
	if err != nil {
		panic(err)
	}

	outPath := filepath.Join(dir, "lookup.go")
	err = os.WriteFile(outPath, buf.Bytes(), 0644)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Generated %s\n", outPath)

	// 2. Generate name_to_color.go
	tName := template.New("nameToColor")
	tName.Funcs(template.FuncMap{"lower": strings.ToLower})

	tName, err = tName.Parse(nameToColorTmpl)
	if err != nil {
		panic(err)
	}

	var bufName bytes.Buffer
	err = tName.Execute(&bufName, struct {
		Pkg    string
		Colors []Color
	}{
		Pkg:    pkgName,
		Colors: colors,
	})
	if err != nil {
		panic(err)
	}

	outNamePath := filepath.Join(dir, "name_to_color.go")
	err = os.WriteFile(outNamePath, bufName.Bytes(), 0644)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Generated %s\n", outNamePath)

	// 3. Generate color_to_name.go
	tColor := template.New("colorToName")
	tColor.Funcs(template.FuncMap{"lower": strings.ToLower})

	tColor, err = tColor.Parse(colorToNameTmpl)
	if err != nil {
		panic(err)
	}

	var bufColor bytes.Buffer
	err = tColor.Execute(&bufColor, struct {
		Pkg    string
		Colors []Color
	}{
		Pkg:    pkgName,
		Colors: colors,
	})
	if err != nil {
		panic(err)
	}

	outColorPath := filepath.Join(dir, "color_to_name.go")
	err = os.WriteFile(outColorPath, bufColor.Bytes(), 0644)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Generated %s\n", outColorPath)

	// 4. Generate maps_sync_test.go
	tSync := template.New("syncTest")
	tSync, err = tSync.Parse(syncTestTmpl)
	if err != nil {
		panic(err)
	}
	var bufSync bytes.Buffer
	err = tSync.Execute(&bufSync, struct {
		Pkg string
	}{
		Pkg: pkgName,
	})
	if err != nil {
		panic(err)
	}
	outSyncPath := filepath.Join(dir, "maps_sync_test.go")
	err = os.WriteFile(outSyncPath, bufSync.Bytes(), 0644)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Generated %s\n", outSyncPath)
}

func generateRootLookup() {
	colors, err := parseColors("colors.go")
	if err != nil {
		panic(err)
	}

	generateLookupFile("colors", ".", colors, true)
}
