// Code generated by generate_lookups.go; DO NOT EDIT.

package crayola

import (
	"testing"
)

func TestMapSync(t *testing.T) {
	// Note: nameToColor maps unique lowercase names to color.RGBA.
	// colorToName maps unique color.RGBA values back to a name.
	// Because some colors map to the exact same color.RGBA value
	// (e.g. Gray and Grey), colorToName can have fewer elements than nameToColor.
	// This test simply verifies that both maps are correctly populated.

	if len(nameToColor) == 0 {
		t.Errorf("nameToColor is empty")
	}
	if len(colorToName) == 0 {
		t.Errorf("colorToName is empty")
	}
	if len(colorToName) > len(nameToColor) {
		t.Errorf("colorToName has more elements (%d) than nameToColor (%d), which should be impossible", len(colorToName), len(nameToColor))
	}
}
