name: CI

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    name: Run ${{ matrix.action }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action: [test, lint, vet, fix, fmt]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Run Test
        if: matrix.action == 'test'
        run: go test -v ./...

      - name: Run Vet
        if: matrix.action == 'vet'
        run: go vet ./...

      - name: Run Lint
        if: matrix.action == 'lint'
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run Fix
        if: matrix.action == 'fix'
        run: go fix ./...

      - name: Run Fmt
        if: matrix.action == 'fmt'
        run: go fmt ./...

      - name: Create Pull Request for Fix
        if: matrix.action == 'fix' && github.event_name == 'workflow_dispatch'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fix: auto-run go fix'
          title: 'Automated go fix update'
          body: 'This PR was automatically generated by running `go fix`.'
          branch: 'auto-fix'
          delete-branch: true

      - name: Create Pull Request for Fmt
        if: matrix.action == 'fmt' && github.event_name == 'workflow_dispatch'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fmt: auto-run go fmt'
          title: 'Automated go fmt update'
          body: 'This PR was automatically generated by running `go fmt`.'
          branch: 'auto-fmt'
          delete-branch: true
