// Code generated by generator/lookups/main.go; DO NOT EDIT.

package web

import (
	"image/color"
	"strings"
)

// FromString returns the color associated with the given name.
// It supports both exact matches and case-insensitive matches.
func FromString(name string) (color.RGBA, bool) {
	c, ok := nameToColor[strings.ToLower(name)]
	return c, ok
}

// ToString returns the name associated with the given color.
// If the color is not found, an empty string is returned.
func ToString(c color.RGBA) string {
	return colorToName[c]
}
